version: '3.4'

services:
  mock-server:
    image: bla/mock-server:latest
    build:
      context: ./MockServer/Server
      dockerfile: Dockerfile
    networks:
      - app-network  

  mock-mocker:
    image: bla/mock-mocker:latest
    build:
      context: ./MockServer/Mocker
      dockerfile: Dockerfile
    depends_on:
      - mock-server
    networks:
      - app-network 
    environment:
      URL_MOCK_SERVER: mock-server 
      URL_MOCK_SERVER_PORT: 1080

networks:
  app-network:
    driver: bridge